### ISSUE TITLE
[Feature] Make implementation of recent posts in blog-index.html and related posts in program-index.html from same style rules

### ISSUE THREAD

**Issue by egbadon-victor** [creativecommons/vocabulary#172]
## Problem

I noticed this when I was working on issue #110. While there are many occurences of  the structure `.posts .post`, this feature targets the occurences with the specific implementation `.posts > .post > ul` ( which I would refer to as the "post grid" implementation). There are 3 occurences of this;

- `blog-index.html` ( Recent posts)
- `program-index.html` (Related posts)
- `blog-post.html` (Related posts)

The grid implementation of these occurences are controlled by the ul element nested in the post component. While it is referenced as
`main article.posts.related ul` when being styled for `program-index.html` and `blog-post.html`, it is referenced as `blog-index main .posts ul` when being styled for `blog-index.html`. This means that managing these grids would require changes to be made in 2 different css rules, meanwhile their structure is similar, and therefore can be handled by one.

Implementing this feature would see that all "post grid" implementations be handled by the same css rules, so as to make the codebase more maintainable

## Description

This feature would refactor the current implementation of all "post grids" to be handled by the following css rule, `.posts article.post ul`. This would mean that all styles for "post grids" can be handled by the same CSS rule.

## Alternatives

Leave the current implementation as is.

## Implementation

- [X] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Hi @egbadon-victor and thanks for this contribution. You are correct that these are handled separate, but that's intentional. Related posts are a modified version of Recent posts, and therefore are two completely different contexts within which .posts can be found. Their separation is one of contextual modularity, and not just a matter of combining styles for efficiency. Their structure may be similar at current, but it may not stay that way, and as they are differing contexts the duplication of stylings also pins changes to each of them more concisely. 

If the styles were combined, and a changed needed to be made to one that was not necessary for the other, then the styles would have to be re-split or more specific override styles would need to be created to do so. This is a case where efficiency in edits would sacrifice degrees of contextual modularity.

I think for now within the current scope this wouldn't be something we'd want to change, as its intended structure.

**Comment by egbadon-victor** [comment]
Hi @possumbilities  this is perfectly understood. The idea that it might not remain so solidifies the need to keep them seperate. Thank you for the clarification!
