### ISSUE TITLE
[Feature] Make search input required.

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#76]
Hello @possumbilities  could you close or block this issue? This is the wrong repo for it. I've opened it in the right repo. Thank you.

**Comment by Queen-codes** [comment]
hello @SisiVero .you can close the issue yourself. Scroll down to the end of the page on your issue and you should see the 'Close issue' button. There's a dropdown on the button, by the side of the 'Close issue' text. Clicking on the dropdown will bring two options. Since you said this is the wrong repo for the issue, you can just click on the 'Close as not planned option'. I hope I managed to make this clear enough.

**Comment by SisiVero** [comment]
Thank you. Let me do that
